### ISSUE TITLE
Assert that `adds` and `subtracts` point to valid variables

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-core#150] opened 2024-02-01 13:25 UTC
When a developer uses an undefined variable in a formula, Policyengine-Core stops program execution and helpfully says the variable is undefined in the current tax-benefit system.

But when a developer uses an undefined variable in an `adds` list or in a `subtracts` list (say, because of a typo in the variable name), Policyengine-Core seems to skip that undefined variable (essentially treating it as an array of zeros) without raising an error.   This behavior is not helpful.

Can the `adds` and `subtracts` logic with respect to undefined variables be enhanced to be the same as the behavior in formulas?

**Comment by MaxGhenis** [comment] 2024-02-01 19:16
Duplicate of #66

**Closed by MaxGhenis** 2024-02-01 19:16 UTC
